var hickey_json = {
	infor: {
		cvName:'史浩的简历',
		description:'Hellow Word',
		job:'前端工程师'
	},
	inforList: [
		{
			title:'个人信息',
			msg:'史浩/男/22岁'
		},
		{
			title:'学历',
			msg:'本科'
		},
		{

			title:'博客园',
			msg:'http://www.cnblogs.com/shihao905',
			url: 'http://www.cnblogs.com/shihao905'
		},
		{
			title:'GitHub',
			msg:'https://github.com/shihao905',
			url: 'https://github.com/shihao905'
		}
	],
	contactMe:[
		{
			className:{'icon-mail-alt':true},
			title:'邮箱',
			address:'519547015@qq.com'
		},
		{
			className:{'icon-wechat':true},
			title:'微信',
			address:'Hickey'
		},
		{
			className:{'icon-qq':true},
			title:'QQ',
			address:'519547015'
		}
	],
	skill:[
		{title:'HTML/CSS',length:'85%'},
		{title:'sass',length:'70%'},
		{title:'javascript',length:'80%'},
		{title:'jQuery',length:'70%'},
		{title:'VueJs',length:'60%'},
		{title:'requireJs',length:'50%'}
	],
	note:[
		'我是一个充满活力，热爱前端事业，并为之一直前进的人。',
		'希望寻找一个关于webApp开发的工作'
	],
	project:[
		{
			type:'明博教育科技股份有限公司(2016.03-至今)',
			list:[
				{
					name:'优课智慧教育云平台',
					msg:'优课教育智慧云平台属于一种教育公共服务平台，主要是为师生打造数字化校园，实现校园信息化管理的一种产品。主要参与平台整体、应用模块的前端开发工作，主要完成页面的ui工作以及部分模块前后台数据交互以及维护工作。',
					links:[{title:'项目地址',url:'http://demo2.yun.myuclass.com/'}],
					images:['./dist/images/pt.jpg']
				},
				{
					name:'优课智慧教育云平台社区（人人通空间）',
					msg:'该产品主要为区域内的（家庭+学校+教育局）提供一个公共的社区交流平台。<br/>主要负责前端的整体架构，部分模块功能开发,主要基于jQuery库进行开发，requireJs进行js模块开发及管理，sass进行项目的样式开发工作，运用Gulp来管理整体项目打包工作',
					links:[{title:'项目地址',url:'http://demo2.yun.myuclass.com/renrentong/JCenterHome/home/index.html?spaceId=832c786dbce8407488b0ebc7050319dd&spaceType=2'}],
					images:['./dist/images/rrt.jpg']
				}
			]
		},
		{
			type:'山西大麦兄弟科技有限公司(2015.04-2015.10)',
			list:[
				{
					name:'大麦电商',
					msg:'主要负责网站的样式布局以及维护工作'
				}
			]
		},
		{
			type:'个人作品',
			list:[
				{
					name:'在线版个人简历',
					msg:'基于 sass+vueJs+gulp 构建的在线版个人简历',
					links:[{title:'源码',url:'https://github.com/shihao905/cv'},{title:'Demo',url:'https://shihao905.github.io/cv/'}],
					images:['./dist/images/cv.jpg']
				},
				{
					name:'经典游戏-扫雷',
					msg:'基于原生js还原经典小游戏-扫雷，支持初级、中级、高级三种难度',
					links:[{title:'源码',url:'https://github.com/shihao905/mineGame'},{title:'Demo',url:'https://shihao905.github.io/mineGame/'}],
					images:['./dist/images/mine1.jpg','./dist/images/mine2.jpg']
				},
				{
					name:'一个多功能的分页插件',
					msg:'基于原生js,面向对象开发的多功能分页插件',
					links:[{title:'源码',url:'https://github.com/shihao905/paging'},{title:'Demo',url:'https://shihao905.github.io/paging/'}],
				},
				{
					name:'仿天猫首页',
					msg:'基于HTML+CSS布局，兼容ie6+以及现代浏览器',
					links:[{title:'源码',url:'https://github.com/shihao905/tmall'},{title:'Demo',url:'https://shihao905.github.io/tmall'}],
					images:['./dist/images/tmall1.jpg','./dist/images/tmall2.jpg']
				},
				{
					name:'仿移动端天猫首页',
					msg:'基于HTML+CSS布局，适配大部分移动端产品',
					links:[{title:'源码',url:'https://github.com/shihao905/tmallmobiles'},{title:'Demo',url:'https://shihao905.github.io/tmallmobiles/'}],
					images:['./dist/images/tmallm.jpg']
				},
				{
					name:'响应式网站',
					msg:'基于CSS媒体查询布局，适配PC端+移动端',
					links:[{title:'源码',url:'https://github.com/shihao905/Responsive'},{title:'Demo',url:'https://shihao905.github.io/Responsive/'}],
					images:['./dist/images/xy.jpg']
				}
			]
		}

	]

}